name: Release

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  release:
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
          run: ./gradlew assembleRelease

      - name: Create Release
        uses: actions/create-release@v1
        with:
          artifacts: "app/build/outputs/apk/release/mall_release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
