name: Android CI

on:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
          run: chmod +x gradlew

      - name: Build with Gradle
          run: ./gradlew assembleRelease

      - name: Create Release
        uses: actions/create-release@v3
        with:
          artifacts: "app/build/outputs/apk/release/mall_release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
